# fly.toml app configuration file generated for wefly-rest on 2024-09-29T15:29:21+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wefly-rest'
primary_region = 'sin'

[build]

[env]
  APP_ENV = 'production'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'wefly'
  DB_HOST = 'restoapp-db.internal'
  DB_PORT = '5432'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
